version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "eslint*"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "vitest*"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "rollup*"
          - "esbuild*"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"

  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]
    groups:
      express:
        patterns:
          - "express*"
          - "@types/express*"
      database:
        patterns:
          - "*sql*"
          - "*db*"
          - "prisma*"
          - "mongoose*"
      security:
        patterns:
          - "helmet*"
          - "cors*"
          - "bcrypt*"
          - "jsonwebtoken*"
      monitoring:
        patterns:
          - "winston*"
          - "morgan*"
          - "pino*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"