[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  # Configurações de segurança para evitar detecção de secrets
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,node_modules/**,.git/**,public/**,*.js,*.ts,*.tsx,*.jsx"
  SECRETS_SCAN_OMIT_KEYS = "VITE_GROQ_API_KEY,GROQ_API_KEY"
  # Configurações adicionais de build
  CI = "true"
  NODE_ENV = "production"

# Configuração do secrets scanning
[build.processing]
  skip_processing = false

# Configurações de segurança
[context.production.environment]
  # As variáveis de ambiente serão configuradas no painel do Netlify