services:
  - type: web
    name: aithos-rag-api
    env: node
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/health
    
  - type: static
    name: aithos-rag-frontend
    buildCommand: npm install && npm run build
    publishDir: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: aithos-rag-api
          property: host